version: '3.7'
services:
    kong:
        image: "elifesciences/kong:{{ pillar.api_gateway.kong_container.image_tag }}"
        hostname: {{ salt['elife.cfg']('project.full_hostname') }} # "prod--gateway.elifesciences.org"
        environment:
            NEW_RELIC_ENABLED: "{{ pillar.elife.newrelic.enabled }}"
        logging: # https://docs.docker.com/compose/compose-file/#logging
            driver: journald
            options:
                # use 'kong' instead of (obscure) process ID
                tag: "kong"
        # so we can access 'localhost' for postgresql on port 5432
        network_mode: "host"
        ports:
            - "8000:8000" # kong
            - "8001:8001" # kong admin
        volumes:
            # salt-rendered config
            - /opt/kong/kong.conf:/etc/kong/kong.conf
            - /opt/kong/nginx_kong.lua:/usr/local/share/lua/5.1/kong/templates/nginx_kong.lua

            # directories (host:container)
            # these paths are specified in `loris2.conf`
            - /var/log/kong:/var/log/kong
            - /usr/local/kong/logs:/usr/local/kong/logs
